### ISSUE TITLE
Review process pagination types

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer#122]
Doing some changes, I've found out some weird types in the elections list. On one side, the `filters` should allow setting the `limit`, since it's just an object spread to the method, which already allows setting the limit:
![imatge](https://github.com/user-attachments/assets/d85fc618-c25a-447b-b22a-45d900818cee)

On the other hand, the elections list is actually returning more election information than we've typed, not just its id, but the typing here only returns the election id:
![imatge](https://github.com/user-attachments/assets/13f1d40c-4c86-4614-b6df-b45753ea649d)

> [!NOTE]
> Do not use the curl calls as a reference for the types. Instead, check the actual types returned by the SDK, or simply log the data received. The SDK does some magic and most information is actually provided (in this case, probably the entire election data is returned already)

**Comment by selankon** [comment]
For the first thing, it was my fault, I omitted the limit I don't remember for which reason. https://github.com/vocdoni/explorer/pull/123/commits/51ad232e4f7fa3b4e26fab58241f5d1bea5d7ccf

But for the second thing... I don't understand you. You are seeing only the id because the election is of type ` PublishedElection | ArchivedElection | InvalidElection` to access to all the properties you have to cast the election to `PublishedElection`
