### ISSUE TITLE
Improve rendering of failing elections

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/explorer#27]
i.e. https://vocdoni-explorer-stg.netlify.app/process/b31dff61814d0e39f9b3bf2b71bc37a8bb312f6c4d8965f1406f030800000000

Instead of just crashing in the react-router-dom level, maybe these should still render the process view component, but instantiating an InvalidElection instead (it's something that may require manual intervention, since the InvalidElections are only returned by the client fetchElections method, which we are NOT using here).

**Comment by selankon** [comment]
The idea is to try to show the most parts of the election that is possible. 

Maybe, showing the error on the top, and then the raw button with the malformed election object or wathever. 

Atm is not possible to fix this because the method fetch election throw an exception and the raw election object is not possible ot be shown.

**Comment by selankon** [comment]
To fix this issue we need to know how this other will be resolved https://github.com/vocdoni/vocdoni-sdk/issues/391 so I pause it until then

**Comment by selankon** [comment]
Awaiting new SDK version

**Comment by selankon** [comment]
The SDK implementation only allows to do this https://github.com/vocdoni/explorer/pull/60
