### ISSUE TITLE
Improve filter search UX

### ISSUE THREAD

**Issue by selankon** [vocdoni/explorer#40]
Actually, the filter is applied, for example on elections, and the ui seems unresponsive. 

Under the hood the SDK is making calls and doing things.  We have to improve the UX for this:

- Maybe show a loader when the SDK starts to search
- Do only one try instead of the actual 4
- Show the error faster. 

Realted to https://github.com/vocdoni/explorer/issues/24

**Comment by elboletaire** [comment]
Also kinda related to #29

**Comment by selankon** [comment]
This can be useful https://github.com/vocdoni/vote-frame/blob/b2820bb2d8cc45906166902776497c8056177e0e/webapp/src/components/Poll/Information.tsx#L28

**Comment by elboletaire** [comment]
BTW note I tried adding some feedback yesterday, but due to how most views are created using a component that only accepts children, rightComponent and given we use the children to either render a single list or more components on it, a generic component could not be created at the time.

My efforts where truncated as soon as I saw the process list, where the spinner/progressbar was shown over the filters, rather than over the list of items as I'd would expect

![imatge](https://github.com/vocdoni/explorer/assets/153305/89932cb3-6bae-4c45-89da-783c73deaf84)

**Comment by elboletaire** [comment]
Closed by #42
